site_name: WGPN Docs
theme:
  logo: assets/logo.png
  favicon: assets/logo.png
  name: material
  palette:
    - scheme: default
      toggle:
          icon: material/toggle-switch-off-outline
          name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto

plugins:
  - search:
      lang: ru

extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/wg_vpn_bot

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg